### ISSUE TITLE
What is the use case for computation frames?

### ISSUE THREAD

**Issue by jgarvin** [amakelov/mandala#30]
I read the [Tidy Computations](https://amakelov.github.io/mandala/blog/01_cf/) page on them but I'm still not sure why I would use them for anything other than input for a visualizer, which they seem like overkill for (you could just recursively spit out graph viz dot syntax if that was all you wanted to do). Feel like I'm still missing: what motivated adding them? They seem separate from just supporting fine grained memoization.

**Comment by amakelov** [comment]
Thanks for the question - computation frames are used to examine and manipulate the contents of the storage in a more declarative way than memoization. The visualization aspect is certainly not the main use case, and is there just to get the idea across, as well as help interface with computation frames. Computation frames are a mostly separate module from memoization for the purposes of code modularity, but they are definitely designed to be used in tandem.

`mandala` aims to be a complete data management solution for computational experiments. Fine-grained memoization is great for iterating on experiments, making sure work is not lost, and pulling results from storage without writing extra storage-related code. The main drawback of memoization for data management is that it is an "imperative" way to access storage; it heavily depends on you having access to the code you ran to generate some results and/or knowing precisely what inputs to provide in order to retrace the memoized function calls.

This works well until your project grows and you no longer remember all the things you ran. Or, for a simpler scenario, imagine accidentally deleting all your code but not the `mandala` storage. In a sense, all your results are still there, but in a very unusable form: you'd need to look inside the memoization tables and do a lot of detective work to piece together what function was called on the output of what other functions to recover your workflow. Computation frames are a way to automate this and explore the storage more systematically. 

There are also situations when you want to delete some results in a declarative way. When you delete something, it also makes sense to delete all results that depend on it, which may be annoying to do using the memoization-as-storage-interface (because there may be lots of such things and/or the code computing them may be gone). Computation frames automatically find all dependencies and clean them up.

Let me know if this clears things up or completely missed the point of your question, and I'm happy to provide more detailed answers!

**Comment by jgarvin** [comment]
Thanks that makes sense
